spring.datasource.url=jdbc:postgresql://localhost:5432/festa_formatura
spring.datasource.username=postgres
spring.datasource.password=oneda3264
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true